name: Gerar Executavel Windows

# O script vai rodar toda vez que você fizer um push na branch 'main'
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest # Pede ao GitHub para usar um servidor Windows

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar o Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Versão bem estável para o PyInstaller

    - name: Instalar dependências e o PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Compilar o executável (.exe) com Ícone
      # O --noconsole esconde a tela preta do terminal
      # O --onefile junta tudo num arquivo só
      # O --icon="icon.ico" embute a imagem no executável final
      run: |
        pyinstaller --noconsole --onefile --icon="icon.ico" --name "Robo_PDF" app.py

    - name: Disponibilizar o arquivo para download
      uses: actions/upload-artifact@v4
      with:
        name: MPAC_Utilitario_PDF_Final
        path: dist/MPAC_Utilitario_PDF.exe