name: Gerar Executavel Windows

on:
  push:
    branches: [ "main" ]

# Força o uso da versão mais atual e segura do Node.js (resolve o aviso amarelo)
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar o Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 

    - name: Instalar dependências e o PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Compilar o executável (.exe)
      # Aqui está o seu novo nome: Robo_PDF. Lembre-se de ter o icon.ico no repositório!
      run: |
        pyinstaller --noconsole --onefile --icon="icon.ico" --name "Robo_PDF" app.py

    - name: Disponibilizar o arquivo para download
      uses: actions/upload-artifact@v4
      with:
        name: Robo_PDF_Final
        # Aqui consertamos o caminho para ele procurar o arquivo com o nome certo:
        path: dist/Robo_PDF.exe